version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: carbot-monitoring-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - carbot-monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"

  loki:
    image: grafana/loki:2.8.2
    container_name: carbot-monitoring-loki
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - carbot-monitoring

  promtail:
    image: grafana/promtail:2.8.2
    container_name: carbot-monitoring-promtail
    volumes:
      - ../logs:/var/log
      - ./promtail/config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - carbot-monitoring
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.0.3
    container_name: carbot-monitoring-grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    networks:
      - carbot-monitoring

networks:
  carbot-monitoring:
    driver: bridge
