export const AUTH_ROUTES = {
    ROOT: '/',
    HEALTH: '/health',
    VERSION: '/version',
    AUTH: {
        GOOGLE: '/google',
        GOOGLE_CALLBACK: '/google/callback',
        REGISTER: '/register',
        REGISTER_TENANT: '/register-tenant',
        LOGIN: '/login',
        SUPER_LOGIN: '/super-login',
        FORGOT_PASSWORD: '/forgot-password',
        RESET_PASSWORD: '/reset-password',
        REFRESH_TOKEN: '/refresh-token',
        VALIDATE_TOKEN: '/validate-token',
        PROFILE: '/profile',
        MY_TENANT: '/my-tenant',
        CHANGE_PASSWORD: '/change-password',
        REQUEST_OTP: '/request-otp',
        RESEND_OTP: '/resend-otp',
        VERIFY_OTP: '/verify-otp',
        LOGOUT: '/logout',
    },
    SUPER_ADMIN: {
        TENANTS: '/tenants',
        TENANT_BY_ID: '/tenants/:id',
        TENANT_FORM_FIELDS: '/tenants/:tenantId/form-fields',
        DASHBOARD_STATS: '/dashboard/stats',
        SYSTEM_SETTINGS: '/settings',
    }
} as const;
