apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: api-gateway-cfg

build:
  artifacts:
    - image: carbot-api-gateway
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

deploy:
  kubectl: {}
manifests:
  rawYaml:
    - ./k8s/*
